### PR TITLE
Fix vertical-center-xs

### PR DESCRIPTION
**Pull request by jfeldstein**
There is a lot of duplication among the vertical center-* classes. 

Where are there two different implementations, when one doesn't work?

### CODE REVIEW

**Comment by ComeDownToUs** [comment]
vertical centering is really difficult, I've tried coming up with renames and it takes about 6 words split by hyphens to describe them (which needs to be done for them to make any sense so I'm on it)

the most generically named one just vertically aligns columns within a row of an unspecified height. `valign-bootstrap-columns` ?

vertical-center-solo, the content of which is the same as vertical-center-xs, will center a solitary column within a row of a fixed height. so something like `vcenter-in-fixed-height-parent`

vertical-center-xs is for text that needs to be centered within an element on mobile (for example an element that's given a height to take up the full screen on mobile, but would be a huge space hog on desktop to be doing that), the media query for desktop needs to override these specs
`vcenter-fixed-height-parent-xs` ?

**Comment by jfeldstein** [comment]
Ah, I didn't realize there were nesting requirements for these to work.

This family of styles might be easier to read if they were grouped together (like in their own file) It'd force all the required nesting and all the options to be visible in one place. 

What do you think>

**Comment by ComeDownToUs** [comment]
Agreed, you kind of have to approach anything relating to vertical centering with an awareness that the solutions are quite convoluted so putting them into a file of their own would help that for sure.

**Comment by jfeldstein** [comment]
Are you planning to make that file here, or in #10 ?

**Comment by jfeldstein** [comment]
Closing this. Please implement a refactor of vertical alignment styles in #10

**Pull request closed without merging**
